name: Test Secret

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Print WAKATIME_API_KEY
        run: echo "WAKATIME_API_KEY is $WAKATIME_API_KEY"
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
